# Generated by Django 2.1.2 on 2018-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('class_name', models.CharField(choices=[('Shielder', 'シールダー'), ('Saber', 'セイバー'), ('Archer', 'アーチャー'), ('Lancer', 'ランサー'), ('Rider', 'ライダー'), ('Caster', 'キャスター'), ('Assassin', 'アサシン'), ('Berserker', 'バーサーカー'), ('Ruler', 'ルーラー'), ('Avenger', 'アベンジャー'), ('MoonCancer', 'ムーンキャンサー'), ('Alterego', 'アルターエゴ'), ('Foreigner', 'フォーリナー')], default='Saber', max_length=16)),
                ('rarity', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
