# Generated by Django 2.1.2 on 2018-10-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rank', models.CharField(blank=True, default='', max_length=4)),
                ('CT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True)),
                ('level1', models.FloatField(blank=True, null=True)),
                ('level2', models.FloatField(blank=True, null=True)),
                ('level3', models.FloatField(blank=True, null=True)),
                ('level4', models.FloatField(blank=True, null=True)),
                ('level5', models.FloatField(blank=True, null=True)),
                ('level6', models.FloatField(blank=True, null=True)),
                ('level7', models.FloatField(blank=True, null=True)),
                ('level8', models.FloatField(blank=True, null=True)),
                ('level9', models.FloatField(blank=True, null=True)),
                ('level10', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('text', models.TextField(default='テキスト')),
            ],
        ),
        migrations.CreateModel(
            name='MysticCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('Quick', 'Quick'), ('Arts', 'Arts'), ('Buster', 'Buster')], default='Buster', max_length=8)),
                ('type', models.CharField(choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('yomi', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=4)),
                ('anti', models.CharField(blank=True, default='', max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('value4', models.FloatField(blank=True, null=True)),
                ('value5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasmEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True)),
                ('OC', models.BooleanField(default=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('value4', models.FloatField(blank=True, null=True)),
                ('value5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rank', models.CharField(blank=True, default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('class_name', models.CharField(choices=[('Shielder', 'シールダー'), ('Saber', 'セイバー'), ('Archer', 'アーチャー'), ('Lancer', 'ランサー'), ('Rider', 'ライダー'), ('Caster', 'キャスター'), ('Assassin', 'アサシン'), ('Berserker', 'バーサーカー'), ('Ruler', 'ルーラー'), ('Avenger', 'アベンジャー'), ('MoonCancer', 'ムーンキャンサー'), ('Alterego', 'アルターエゴ'), ('Foreigner', 'フォーリナー')], default='Saber', max_length=16)),
                ('rarity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('command_cards_distribution', models.CharField(choices=[('quick3', 'QQQAB'), ('arts3', 'QAAAB'), ('buster3', 'QABBB'), ('quick1', 'QAABB'), ('arts1', 'QQABB'), ('buster1', 'QQAAB')], default='quick1', max_length=8)),
                ('quick_hits', models.IntegerField(default=1)),
                ('arts_hits', models.IntegerField(default=1)),
                ('buster_hits', models.IntegerField(default=1)),
                ('extra_hits', models.IntegerField(default=1)),
                ('base_HP', models.IntegerField(default=0)),
                ('max_HP', models.IntegerField(default=0)),
                ('palingenesis_HP', models.IntegerField(default=0)),
                ('base_ATK', models.IntegerField(default=0)),
                ('max_ATK', models.IntegerField(default=0)),
                ('palingenesis_ATK', models.IntegerField(default=0)),
                ('attribute', models.CharField(choices=[('sky', '天'), ('earth', '地'), ('man', '人'), ('star', '星'), ('beast', '獣')], default='man', max_length=8)),
                ('alignment1', models.CharField(choices=[('cosmos', '秩序'), ('chaos', '混沌'), ('neutral', '中立'), ('other', 'その他')], default='cosmos', max_length=8)),
                ('alignment2', models.CharField(choices=[('good', '善'), ('evil', '悪'), ('neutral', '中庸'), ('insane', '狂'), ('other', 'その他')], default='good', max_length=8)),
                ('sex', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], default='male', max_length=8)),
                ('star_getting_rate', models.FloatField(default=0)),
                ('star_focusing_rate', models.FloatField(default=0)),
                ('death_rate', models.FloatField(default=100)),
                ('NP_with_attack', models.FloatField(default=0)),
                ('NP_with_damage', models.FloatField(default=0)),
                ('active_skill', models.ManyToManyField(to='fgo_master_app.ActiveSkill')),
                ('passive_skill', models.ManyToManyField(to='fgo_master_app.PassiveSkill')),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('QP', 'QP')], max_length=32)),
                ('ascension1', models.IntegerField(default=0)),
                ('ascension2', models.IntegerField(default=0)),
                ('ascension3', models.IntegerField(default=0)),
                ('ascension4', models.IntegerField(default=0)),
                ('skill_up1', models.IntegerField(default=0)),
                ('skill_up2', models.IntegerField(default=0)),
                ('skill_up3', models.IntegerField(default=0)),
                ('skill_up4', models.IntegerField(default=0)),
                ('skill_up5', models.IntegerField(default=0)),
                ('skill_up6', models.IntegerField(default=0)),
                ('skill_up7', models.IntegerField(default=0)),
                ('skill_up8', models.IntegerField(default=0)),
                ('skill_up9', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='servant',
            name='synthesis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fgo_master_app.Synthesis'),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='effect',
            field=models.ManyToManyField(related_name='passive_skill', to='fgo_master_app.PassiveSkillEffect'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='effect',
            field=models.ManyToManyField(related_name='noble_phantasm', to='fgo_master_app.NoblePhantasmEffect'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noble_phantasm', to='fgo_master_app.Servant'),
        ),
        migrations.AddField(
            model_name='activeskill',
            name='effect',
            field=models.ManyToManyField(related_name='active_skill', to='fgo_master_app.ActiveSkillEffect'),
        ),
    ]
