# Generated by Django 2.1.2 on 2018-10-26 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('rank', models.CharField(blank=True, default='', max_length=4)),
                ('CT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], default='', max_length=8)),
                ('value', models.FloatField(blank=True, null=True)),
                ('step', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommandCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField(default='テキスト')),
            ],
        ),
        migrations.CreateModel(
            name='MysticCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(choices=[('Quick', 'Quick'), ('Arts', 'Arts'), ('Buster', 'Buster')], default='Buster', max_length=8)),
                ('type', models.CharField(choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('yomi', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=4)),
                ('anti', models.CharField(blank=True, default='', max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('value4', models.FloatField(blank=True, null=True)),
                ('value5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasmEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True)),
                ('OC', models.BooleanField(default=True)),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('value4', models.FloatField(blank=True, null=True)),
                ('value5', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('rank', models.CharField(blank=True, default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], default='', max_length=8)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('class_name', models.CharField(choices=[('Shielder', 'シールダー'), ('Saber', 'セイバー'), ('Archer', 'アーチャー'), ('Lancer', 'ランサー'), ('Rider', 'ライダー'), ('Caster', 'キャスター'), ('Assassin', 'アサシン'), ('Berserker', 'バーサーカー'), ('Ruler', 'ルーラー'), ('Avenger', 'アベンジャー'), ('MoonCancer', 'ムーンキャンサー'), ('Alterego', 'アルターエゴ'), ('Foreigner', 'フォーリナー')], default='Saber', max_length=16)),
                ('rarity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('command_cards_distribution', models.CharField(choices=[('Quick3', 'QQQAB'), ('Arts3', 'QAAAB'), ('Buster3', 'QABBB'), ('Quick1', 'QAABB'), ('Arts1', 'QQABB'), ('Buster1', 'QQAAB')], default='Quick1', max_length=8)),
                ('quick_hits', models.IntegerField(default=1)),
                ('arts_hits', models.IntegerField(default=1)),
                ('buster_hits', models.IntegerField(default=1)),
                ('extra_hits', models.IntegerField(default=1)),
                ('base_HP', models.IntegerField(default=0)),
                ('max_HP', models.IntegerField(default=0)),
                ('palingenesis_HP', models.IntegerField(default=0)),
                ('base_ATK', models.IntegerField(default=0)),
                ('max_ATK', models.IntegerField(default=0)),
                ('palingenesis_ATK', models.IntegerField(default=0)),
                ('attribute', models.CharField(choices=[('Sky', '天'), ('Earth', '地'), ('Man', '人'), ('Star', '星'), ('Beast', '獣')], default='Man', max_length=8)),
                ('alignment1', models.CharField(choices=[('Lawful', '秩序'), ('Chaotic', '混沌'), ('Neutral', '中立'), ('Other', 'その他')], default='Lawful', max_length=8)),
                ('alignment2', models.CharField(choices=[('Good', '善'), ('Evil', '悪'), ('Neutral', '中庸'), ('Madness', '狂'), ('Other', 'その他')], default='Good', max_length=8)),
                ('gender', models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Other', 'その他')], default='Female', max_length=8)),
                ('star_drop_rate', models.FloatField(default=0)),
                ('star_gather_rate', models.FloatField(default=0)),
                ('death_rate', models.FloatField(default=100)),
                ('NP_with_attack', models.FloatField(default=0)),
                ('NP_gain_from_damage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('QP', 'QP')], max_length=32)),
                ('ascension1', models.IntegerField(default=0)),
                ('ascension2', models.IntegerField(default=0)),
                ('ascension3', models.IntegerField(default=0)),
                ('ascension4', models.IntegerField(default=0)),
                ('skill_up1', models.IntegerField(default=0)),
                ('skill_up2', models.IntegerField(default=0)),
                ('skill_up3', models.IntegerField(default=0)),
                ('skill_up4', models.IntegerField(default=0)),
                ('skill_up5', models.IntegerField(default=0)),
                ('skill_up6', models.IntegerField(default=0)),
                ('skill_up7', models.IntegerField(default=0)),
                ('skill_up8', models.IntegerField(default=0)),
                ('skill_up9', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='effect',
            field=models.ManyToManyField(related_name='passive_skill', to='fgo_master_app.PassiveSkillEffect'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='effect',
            field=models.ManyToManyField(blank=True, null=True, related_name='noble_phantasm', to='fgo_master_app.NoblePhantasmEffect'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noble_phantasm', to='fgo_master_app.Servant'),
        ),
        migrations.AddField(
            model_name='activeskill',
            name='effect',
            field=models.ManyToManyField(related_name='active_skill', to='fgo_master_app.ActiveSkillEffect'),
        ),
    ]
