# Generated by Django 2.1.2 on 2018-10-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeskilleffect',
            old_name='level1',
            new_name='step',
        ),
        migrations.RenameField(
            model_name='activeskilleffect',
            old_name='level10',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level2',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level3',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level4',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level5',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level6',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level7',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level8',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='level9',
        ),
    ]
