# Generated by Django 2.1.2 on 2018-10-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('rank', models.CharField(max_length=4)),
                ('charge_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('yomi', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=8)),
                ('hits', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
                ('rank', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Synthesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('QP', 'QP')], max_length=32)),
                ('ascension1', models.IntegerField(default=0)),
                ('ascension2', models.IntegerField(default=0)),
                ('ascension3', models.IntegerField(default=0)),
                ('ascension4', models.IntegerField(default=0)),
                ('skill_up1', models.IntegerField(default=0)),
                ('skill_up2', models.IntegerField(default=0)),
                ('skill_up3', models.IntegerField(default=0)),
                ('skill_up4', models.IntegerField(default=0)),
                ('skill_up5', models.IntegerField(default=0)),
                ('skill_up6', models.IntegerField(default=0)),
                ('skill_up7', models.IntegerField(default=0)),
                ('skill_up8', models.IntegerField(default=0)),
                ('skill_up9', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='servant',
            name='NP_with_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='NP_with_damage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='alignment1',
            field=models.CharField(choices=[('cosmos', '秩序'), ('chaos', '混沌'), ('neutral', '中立'), ('other', 'その他')], default='cosmos', max_length=8),
        ),
        migrations.AddField(
            model_name='servant',
            name='alignment2',
            field=models.CharField(choices=[('good', '善'), ('evil', '悪'), ('neutral', '中庸'), ('insane', '狂'), ('other', 'その他')], default='good', max_length=8),
        ),
        migrations.AddField(
            model_name='servant',
            name='arts_hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servant',
            name='attribute',
            field=models.CharField(choices=[('sky', '天'), ('earth', '地'), ('man', '人'), ('star', '星'), ('beast', '獣')], default='man', max_length=8),
        ),
        migrations.AddField(
            model_name='servant',
            name='base_ATK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='base_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='buster_hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servant',
            name='command_cards_distribution',
            field=models.CharField(default='quick1', max_length=8),
        ),
        migrations.AddField(
            model_name='servant',
            name='death_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='extra_hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servant',
            name='max_ATK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='max_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='palingenesis_ATK',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='palingenesis_HP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='quick_hits',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servant',
            name='sex',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], default='male', max_length=8),
        ),
        migrations.AddField(
            model_name='servant',
            name='star_focusing_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='star_getting_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servant',
            name='active_skill',
            field=models.ManyToManyField(to='fgo_master_app.ActiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='noble_phantasm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fgo_master_app.NoblePhantasm'),
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skill',
            field=models.ManyToManyField(to='fgo_master_app.PassiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='synthesis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fgo_master_app.Synthesis'),
        ),
    ]
