# Generated by Django 2.1.2 on 2018-10-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0002_auto_20181016_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='NP_with_attack',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='servant',
            name='NP_with_damage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='servant',
            name='death_rate',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='servant',
            name='star_focusing_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='servant',
            name='star_getting_rate',
            field=models.FloatField(default=0),
        ),
    ]
