# Generated by Django 2.1.2 on 2018-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0002_auto_20181205_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='limit_type',
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='attr_limit',
            field=models.CharField(choices=[('Humanoid', '人型'), ('None', 'なし')], default='None', max_length=16, verbose_name='特性制限'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='class_limit',
            field=models.CharField(choices=[('Shilder', 'シールダー'), ('Saber', 'セイバー'), ('Archer', 'アーチャー'), ('Lancer', 'ランサー'), ('Rider', 'ライダー'), ('Caster', 'キャスター'), ('Assassin', 'アサシン'), ('Berserker', 'バーサーカー'), ('Ruler', 'ルーラー'), ('Avenger', 'アベンジャー'), ('MoonCancer', 'ムーンキャンサー'), ('Alterego', 'アルターエゴ'), ('Foreigner', 'フォーリナー'), ('None', 'なし')], default='None', max_length=16, verbose_name='クラス制限'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='effect',
            field=models.CharField(choices=[('Quick', 'Quickカードの性能'), ('Arts', 'Artsカードの性能'), ('Buster', 'Busterカードの性能'), ('Critical', 'クリティカル威力'), ('StarDrop', 'スター発生率'), ('DebuffSuccess', '弱体付与成功率'), ('DamagePlus', '与ダメージプラス状態'), ('DebuffResist', '弱体耐性'), ('DeathResist', '即死耐性'), ('MentalDebuffResist', '精神異常耐性'), ('NPDamaged', '被ダメージ時に獲得するNP'), ('NP_et', '毎ターンNP獲得状態'), ('DeathImmune', '即死無効状態'), ('PowerfulCharmResist', '強力な魅了耐性'), ('DeathEffect', '通常攻撃時に極低確率で即死効果が発生する状態'), ('DEF', '防御力'), ('SpecialAttack', '特攻状態'), ('Healing', 'HP回復量'), ('Star_et', '毎ターンスター2個獲得状態'), ('BurnImmune', 'やけど無効状態')], default='Quick', max_length=32, verbose_name='効果'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='field_limit',
            field=models.CharField(choices=[('WaterSide', '水辺'), ('None', 'なし')], default='None', max_length=16, verbose_name='フィールド制限'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='target',
            field=models.CharField(choices=[('yourself', '自身'), ('all_in_sub_ex_you', '自信を除く味方全体<控え含む>')], default='yourself', max_length=32, verbose_name='対象'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='text',
            field=models.CharField(choices=[('apply', '付与'), ('increase', 'アップ'), ('slightly_increase', '少しアップ'), ('decrease', 'ダウン')], default='increase', max_length=32, verbose_name='程度'),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='値'),
        ),
    ]
