# Generated by Django 2.1.2 on 2018-11-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0002_auto_20181029_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='noblephantasm',
            name='name_en',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='type',
            field=models.CharField(blank=True, choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='effect',
            field=models.ManyToManyField(related_name='noble_phantasm', to='fgo_master_app.NoblePhantasmEffect'),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='type',
            field=models.CharField(blank=True, choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='yomi',
            field=models.CharField(max_length=64),
        ),
    ]
