# Generated by Django 2.1.2 on 2018-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0003_auto_20181016_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CraftEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rarity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MysticCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='anti',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='rank',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='card',
            field=models.CharField(choices=[('Quick', 'Quick'), ('Arts', 'Arts'), ('Buster', 'Buster')], default='Buster', max_length=8),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='rank',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='type',
            field=models.CharField(choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=4),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='servant',
            name='command_cards_distribution',
            field=models.CharField(choices=[('quick3', 'QQQAB'), ('arts3', 'QAAAB'), ('buster3', 'QABBB'), ('quick1', 'QAABB'), ('arts1', 'QQABB'), ('buster1', 'QQAAB')], default='quick1', max_length=8),
        ),
    ]
