# Generated by Django 2.1.2 on 2018-11-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0003_auto_20181106_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeskill',
            name='name_en',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activeskill',
            name='servant',
            field=models.ManyToManyField(related_name='active_skills', to='fgo_master_app.Servant'),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='servant',
            field=models.ManyToManyField(related_name='passive_skills', to='fgo_master_app.Servant'),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='icon',
            field=models.CharField(blank=True, choices=[('ATK_UP', 'ATK_UP.png'), ('.DS_Store', '.DS_Store'), ('Critical_UP', 'Critical_UP.png'), ('Evade', 'Evade.png'), ('OC_UP', 'OC_UP.png'), ('HP_restore', 'HP_restore.png'), ('Quick_Buster_UP', 'Quick_Buster_UP.png'), ('DEF_UP', 'DEF_UP.png'), ('Arts_Quick_Buster_UP', 'Arts_Quick_Buster_UP.png'), ('NP_UP', 'NP_UP.png'), ('Arts_Buster_UP', 'Arts_Buster_UP.png'), ('Arts_UP', 'Arts_UP.png'), ('Turn', 'Turn.png'), ('Invicble', 'Invicble.png'), ('Buster_UP', 'Buster_UP.png'), ('SpecialATK_UP', 'SpecialATK_UP.png'), ('Quick_UP', 'Quick_UP.png'), ('HP_restore_per_turn', 'HP_restore_per_turn.png')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='servant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='noble_phantasm', to='fgo_master_app.Servant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='icon',
            field=models.CharField(blank=True, choices=[('IndependentAction', 'IndependentAction.png'), ('RidingSkill', 'RidingSkill.png'), ('Self-Restoration', 'Self-Restoration.png'), ('ItemConstruction', 'ItemConstruction.png'), ('TerritoryCreation', 'TerritoryCreation.png'), ('PresenceConcealment', 'PresenceConcealment.png'), ('MadnessEnhancement', 'MadnessEnhancement.png'), ('Avenger', 'Avenger.png'), ('MagicResistance', 'MagicResistance.png'), ('OblivionCorrection', 'OblivionCorrection.png')], default='', max_length=64),
        ),
    ]
