# Generated by Django 2.1.2 on 2018-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0004_auto_20181106_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftEssenceEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='activeskill',
            name='servant',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='servant',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='text',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='noblephantasmeffect',
            name='OC',
        ),
        migrations.RemoveField(
            model_name='noblephantasmeffect',
            name='type',
        ),
        migrations.RemoveField(
            model_name='passiveskill',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='passiveskill',
            name='servant',
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='increase',
            field=models.CharField(choices=[('Lv', 'Lv'), ('OC', 'OC')], default='Lv', max_length=2),
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='target',
            field=models.CharField(choices=[('yourself', '自身'), ('all_allies', '味方全体'), ('single_enemy', '敵単体'), ('all_enemies', '敵全体')], default='all_enemies', max_length=8),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='active_skill1',
            field=models.ManyToManyField(related_name='servant_for_skill1', to='fgo_master_app.ActiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='active_skill2',
            field=models.ManyToManyField(related_name='servant_for_skill2', to='fgo_master_app.ActiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='active_skill3',
            field=models.ManyToManyField(related_name='servant_for_skill3', to='fgo_master_app.ActiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='noble_phantasm',
            field=models.ManyToManyField(related_name='servant', to='fgo_master_app.NoblePhantasm'),
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skill1',
            field=models.ManyToManyField(related_name='servant_for_skill1', to='fgo_master_app.PassiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skill2',
            field=models.ManyToManyField(related_name='servant_for_skill2', to='fgo_master_app.PassiveSkill'),
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skill3',
            field=models.ManyToManyField(related_name='servant_for_skill3', to='fgo_master_app.PassiveSkill'),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='anti',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='type',
            field=models.CharField(choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8),
        ),
        migrations.AlterField(
            model_name='servant',
            name='cv',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='servant',
            name='illust',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='servant',
            name='origin',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='servant',
            name='region',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='PassiveSkillEffect',
        ),
    ]
