# Generated by Django 2.1.2 on 2018-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0004_auto_20181017_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeskill',
            name='text',
            field=models.TextField(default='テキスト'),
        ),
        migrations.AddField(
            model_name='craftessence',
            name='text',
            field=models.TextField(default='テキスト'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='text',
            field=models.TextField(default='テキスト'),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='text',
            field=models.TextField(default='テキスト'),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='type',
            field=models.CharField(choices=[('whole', '全体'), ('single', '単体'), ('support', '補助')], default='whole', max_length=8),
        ),
    ]
