# Generated by Django 2.1.2 on 2018-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0005_auto_20181107_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servant',
            name='passive_skill1',
        ),
        migrations.RemoveField(
            model_name='servant',
            name='passive_skill2',
        ),
        migrations.RemoveField(
            model_name='servant',
            name='passive_skill3',
        ),
        migrations.AddField(
            model_name='servant',
            name='passive_skill',
            field=models.ManyToManyField(related_name='servant', to='fgo_master_app.PassiveSkill'),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='target',
            field=models.CharField(choices=[('yourself', '自身'), ('all_allies', '味方全体'), ('single_enemy', '敵単体'), ('all_enemies', '敵全体')], default='all_enemies', max_length=16),
        ),
    ]
