# Generated by Django 2.1.2 on 2018-10-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0005_auto_20181019_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='テキスト')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NoblePhantasmEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='テキスト')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PassiveSkillEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='テキスト')),
                ('value1', models.IntegerField()),
                ('value2', models.IntegerField()),
                ('value3', models.IntegerField()),
                ('value4', models.IntegerField()),
                ('value5', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activeskill',
            name='text',
        ),
        migrations.RemoveField(
            model_name='noblephantasm',
            name='value',
        ),
        migrations.RemoveField(
            model_name='passiveskill',
            name='text',
        ),
        migrations.RemoveField(
            model_name='servant',
            name='noble_phantasm',
        ),
        migrations.AddField(
            model_name='activeskill',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='servant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noble_phantasm', to='fgo_master_app.Servant'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='value1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='value2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='value3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='value4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='value5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activeskill',
            name='effect',
            field=models.ManyToManyField(related_name='active_skill', to='fgo_master_app.NoblePhantasmEffect'),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='effect',
            field=models.ManyToManyField(related_name='noble_phantasm', to='fgo_master_app.NoblePhantasmEffect'),
        ),
        migrations.AddField(
            model_name='passiveskill',
            name='effect',
            field=models.ManyToManyField(related_name='passive_skill', to='fgo_master_app.NoblePhantasmEffect'),
        ),
    ]
