# Generated by Django 2.1.2 on 2018-10-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0006_auto_20181021_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftessence',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
