# Generated by Django 2.1.2 on 2018-10-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fgo_master_app', '0007_auto_20181022_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeskill',
            old_name='charge_time',
            new_name='CT',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='activeskilleffect',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='passiveskilleffect',
            name='value5',
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='duration_type',
            field=models.CharField(blank=True, choices=[('turn', 'ターン'), ('times', '回')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activeskilleffect',
            name='level9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noblephantasm',
            name='turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='OC',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noblephantasmeffect',
            name='turn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passiveskilleffect',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activeskill',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='activeskilleffect',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='craftessence',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='anti',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noble_phantasm', to='fgo_master_app.Servant'),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='value1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='value2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='value3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='value4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasm',
            name='value5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='value1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='value2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='value3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='value4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noblephantasmeffect',
            name='value5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='passiveskill',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='passiveskilleffect',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='servant',
            name='synthesis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fgo_master_app.Synthesis'),
        ),
    ]
